
export const REGISTERED_USER = 'REGISTERED_USER';
export const START_LOADING = 'START_LOADING';

//User Login Data Store
export const APP_SET_USER_DATA = 'APP_SET_USER_DATA';
export const USER_EMAIL_CHANGED = 'USER_EMAIL_CHANGED';
export const USER_PASS_CHANGED = 'USER_PASS_CHANGED';

export const AGENT_FNAME_CHANGED = 'AGENT_FNAME_CHANGED';
export const AGENT_LNAME_CHANGED = 'AGENT_LNAME_CHANGED';
export const AGENT_EMAILID_CHANGED = 'AGENT_EMAILID_CHANGED';
export const AGENT_MOBILENO_CHANGED = 'AGENT_MOBILENO_CHANGED';
export const AGENT_PASSWORD_CHANGED = 'AGENT_PASSWORD_CHANGED';
export const AGENT_USERNAME_CHANGED = 'AGENT_USERNAME_CHANGED';
export const AGENT_BIRTH_DATE = 'USER_BIRTH_DATE';

export const AGENT_ADDRESS_PROOF_TYPE = 'AGENT_ADDRESS_PROOF_TYPE';

export const AGENT_STATE_CHANGED = 'AGENT_STATE_CHANGED';
export const AGENT_ZONE_CHANGED = 'AGENT_ZONE_CHANGED';
export const AGENT_BRANCH_CHANGED = 'AGENT_BRANCH_CHANGED';

export const AGENT_BANKNAME_CHANGED = 'AGENT_BANKNAME_CHANGED';
export const AGENT_BANKBRANCH_CHANGED = 'AGENT_BANKBRANCH_CHANGED';
export const AGENT_ACHOLDER_CHANGED = 'AGENT_ACHOLDER_CHANGED';
export const AGENT_ACCNO_CHANGED = 'AGENT_ACCNO_CHANGED';
export const AGENT_IFSE_CHANGED = 'AGENT_IFSE_CHANGED';

export const AGENT_ACTIVATION = 'AGENT_ACTIVATION';

export const GET_ALL_STATES_SUCCESS = 'GET_ALL_STATES_SUCCESS';
export const GET_ALL_STATES_FAILED = 'GET_ALL_STATES_FAILED';

export const GET_ALL_ZONES_SUCCESS = 'GET_ALL_ZONES_SUCCESS';
export const GET_ALL_ZONES_FAILED = 'GET_ALL_ZONES_FAILED';

export const GET_ALL_BRANCHES_SUCCESS = 'GET_ALL_BRANCHES_SUCCESS';
export const GET_ALL_BRANCHES_FAILED = 'GET_ALL_BRANCHES_FAILED';